### ISSUE TITLE
Onboarding komponenta

### ISSUE THREAD

**Issue by jirizikes** [cesko-digital/audiozpravy#1]
Vytvoření komponenty úvodního onboarding screenu `/app/components/screen-components/onboarding.tsx`

- nadpis bude komponenta heading `app/components/typography/heading.tsx`
- popis bude komponenta description `app/components/typography/description.tsx`
- odkaz bude komponenta mainButton `app/components/buttons/main-button.tsx` -> odkazuje na screen **Topics**
- odkaz na přihlášení zatím zobrazovat nebudeme

- [x] Heading
- [x] Description
- [x] Button
- [x] Login link (zatím schovat)
- [ ] celá komponenta

**Odkaz na Figmu:** https://www.figma.com/file/upqhhjeddV2uimXaad0ZIS/Inovace-zpravodajstvi?node-id=208%3A0

**Ukázka:**

<img width="233" alt="Screenshot 2021-05-27 at 23 17 17" src="https://user-images.githubusercontent.com/47362491/119898124-b24b7080-bf41-11eb-883c-f5e5e66b2e02.png">

**Comment by danielTipelt** [comment]
K teto komponente se hlasim.
