### ISSUE TITLE
APP: Navigace komponenta

### ISSUE THREAD

**Issue by jirizikes** [cesko-digital/audiozpravy#16]
Vytvoření navigace pro přepínání jednotlivých screenů viz. printscreen. 

- [ ] nakódování komponenty
- [ ] přepínání screenů
- [ ] vložení do jednotlivých screenů

**Odkaz na Figmu:** https://www.figma.com/file/upqhhjeddV2uimXaad0ZIS/Inovace-zpravodajstvi?node-id=208%3A0

**Ukázka:**

<img width="492" alt="Screenshot 2021-06-14 at 21 32 16" src="https://user-images.githubusercontent.com/47362491/121948812-00d97700-cd58-11eb-8e1f-4b408ea60bda.png">

**Comment by danielTipelt** [comment]
Jdu do toho
