### ISSUE TITLE
APP: Topics komponenta

### ISSUE THREAD

**Issue by jirizikes** [cesko-digital/audiozpravy#2]
Vytvoření komponenty pro Topics - výběr tématů

**Odkaz na Figmu:** https://www.figma.com/file/upqhhjeddV2uimXaad0ZIS/Inovace-zpravodajstvi?node-id=208%3A0

**Ukázka:**

<img width="218" alt="Screenshot 2021-05-27 at 23 21 26" src="https://user-images.githubusercontent.com/47362491/119898534-461d3c80-bf42-11eb-8e38-2aeadabc1fcd.png">

**Comment by CoffeeladyCZ** [comment]
@jirizikes o tohle issue bych měla zájem :)

**Comment by jirizikes** [comment]
@CoffeeladyCZ super, přiřadil jsem tě k tomu! Díky.
