### ISSUE TITLE
BE: JSON API Endpoint 

### ISSUE THREAD

**Issue by jirizikes** [cesko-digital/audiozpravy#24]
API endpoint který bude vracet data v JSON podobě.

**Comment by clytaemnestra** [comment]
Je potřeba zkopírovat metodu feed z app.py a upravit tak, aby místo HTML vracela JSON. Tzn. když odešlu požadavek GET /.../feed , měla bych dostat odpověď "title": {...} , "link": {...} a to samé pro summary, published, category a audio.

**Comment by Joelino** [comment]
JSON už by to mělo vracet teď. Podívám se na to o víkendu.

**Comment by jirizikes** [comment]
@Joelino Určitě ho vrací? Protože se toho chtěla už chopit @clytaemnestra

**Comment by clytaemnestra** [comment]
Teď jsem to ověřila a vrací JSON, viz obrázek:

![feed-ff](https://user-images.githubusercontent.com/38294198/124354922-dbc97d00-dc0e-11eb-87a3-b0441ce022b5.png)
