### ISSUE TITLE
APP: News komponenta

### ISSUE THREAD

**Issue by jirizikes** [cesko-digital/audiozpravy#3]
Vytvoření komponenty pro News - výpis základního feedu a výpis kategorie

**Spodní navigace je obsažená už v jiném ticketu.**

**Odkaz na Figmu:** https://www.figma.com/file/upqhhjeddV2uimXaad0ZIS/Inovace-zpravodajstvi?node-id=208%3A0

**Ukázka:**

<img width="205" alt="Screenshot 2021-05-27 at 23 22 39" src="https://user-images.githubusercontent.com/47362491/119898684-71a02700-bf42-11eb-8a66-72e771c329b9.png">

**Comment by Terra42** [comment]
@jirizikes vezmu si pro začátek tenhle výpis zpráv

**Comment by jirizikes** [comment]
@Terra42 Super, přiřadil jsem tě k ticketu. Kdyby si potřebovala pomoct, dej vědět můžeme zavolat.
