### ISSUE TITLE
APP: Komponenta přátel

### ISSUE THREAD

**Issue by jirizikes** [cesko-digital/audiozpravy#31]
Nakódování kompoenty přátel podle designu ve Figmě.

*Odkaz na FIgmu:* https://www.figma.com/file/upqhhjeddV2uimXaad0ZIS/Inovace-zpravodajstvi?node-id=208%3A0

<img width="349" alt="Screenshot 2021-07-08 at 10 51 56" src="https://user-images.githubusercontent.com/47362491/124893075-b657bd00-dfda-11eb-8bda-37791604d0aa.png">

**Comment by Terra42** [comment]
Vezmu si tohle issue, díky :)

**Comment by jirizikes** [comment]
@Terra42 Super, díky!
