### ISSUE TITLE
APP: Komponenta kategorií

### ISSUE THREAD

**Issue by jirizikes** [cesko-digital/audiozpravy#32]
Nakódování komponenty kategorií podle návrhu ve Figmě.

*Odkaz na Figmu:* https://www.figma.com/file/upqhhjeddV2uimXaad0ZIS/Inovace-zpravodajstvi?node-id=208%3A0

<img width="385" alt="Screenshot 2021-07-08 at 10 54 18" src="https://user-images.githubusercontent.com/47362491/124893253-db4c3000-dfda-11eb-9050-56dd6752ba82.png">

**Comment by DeepBlue321** [comment]
Dělám na tom

**Comment by jirizikes** [comment]
@DeepBlue321 supr
