### ISSUE TITLE
APP: Player komponenta

### ISSUE THREAD

**Issue by jirizikes** [cesko-digital/audiozpravy#4]
Grafická komponenta přehrávače

https://www.figma.com/file/upqhhjeddV2uimXaad0ZIS/Inovace-zpravodajstvi?node-id=292%3A523

<img width="200" alt="Screenshot 2021-05-27 at 23 23 32" src="https://user-images.githubusercontent.com/47362491/119898817-998f8a80-bf42-11eb-9570-2041dc98f47b.png">

**Comment by danielTipelt** [comment]
Hlasim se k tomu
